@startuml
actor User
Participant WebAppUI
Participant FlaskApp
Participant LLM
Database FAISSVectorDatabase
collections documents

== Dataset Ingestion & Indexing ==
User -> WebAppUI ++: Requests New Vector Database Generation
User -> WebAppUI: Uploads PDFs
WebAppUI -> FlaskApp ++: New Vector Database Generation Request
FlaskApp -> documents: Clear documents folder contents
FlaskApp -> documents: Persist documents in folder
FlaskApp -> FAISSVectorDatabase: Clear Vector Database
FlaskApp -> FlaskApp: Generates new FAISS Vector Database
FlaskApp -> FAISSVectorDatabase: Persist FAISS Database (in filesystem)
FlaskApp --> WebAppUI --: FAISS Generation Response
WebAppUI --> User --: Show Vector Database Generation Status 

== Semantic Search & Contextual Summarization ==
User -> WebAppUI ++: Enters search query
WebAppUI -> FlaskApp ++: Semantic Search Request
FlaskApp -> FlaskApp: Check if FAISS Database exists
alt FAISS database does not exist
    FlaskApp --> WebAppUI: Return Database does not exist error
end
FlaskApp -> FAISSVectorDatabase ++: Search Vector Database using Query
FAISSVectorDatabase --> FlaskApp --: Return Semantically Similar Passage (if found)
alt Passage retrieved
    FlaskApp -> FlaskApp: Find if retrieved passage is "unclear", using NLP
    alt Retrieved Passage is unclear
        FlaskApp -> FlaskApp: Divide Passage into smaller chunks
        loop for each chunk
            FlaskApp -> LLM ++: Rephrase Passage LLM Request
            LLM --> FlaskApp --: Rephrase Passage LLM Response
        end
    end
    FlaskApp -> FlaskApp: Find if passage is "too long"
    alt Passage is too long 
        FlaskApp -> FlaskApp: Divide Passage into smaller chunks
        loop for each chunk
            FlaskApp -> LLM ++: Summarize Passage LLM Request
            LLM --> FlaskApp --: Summarize Passage Response
        end
    end
    FlaskApp --> WebAppUI --: Return Semantic Search Response 
else Passage not found
    FlaskApp --> WebAppUI: Return Generic Response
end
WebAppUI --> User --: Show Semantic Search Results
@enduml