CONFIG_FILE_LOCATION="server/config/.env.development"
GENERIC_MESSAGE_FOR_NO_CHUNK_CASE="**GENERIC MESSAGE**"
PASSAGE_CONFIDENCE_SCORE=0.5
REPHRASE_PASSAGE_THRESHOLD=1000
MAX_LLM_CHUNK_SIZE=500
OVERLAP_SENTENCES_WITHIN_CONSECUTIVE_CHUNKS=2